blank_issues_enabled: false
contact_links:
  - name: asl-help Discussions
    url: https://github.com/just-ero/asl-help/discussions
    about: Have a question about asl-help or how to use it that isn't covered in the documentation? Open a discussion thread!
  - name: Speedrun Tool Development Discord
    url: https://discord.gg/cpYsxz7
    about: To get more immediate help, join this Discord server.
  - name: There is a problem with a script which is not caused by asl-help.
    url: https://github.com/just-ero/asl-help#third-party-notice
    about: We do not cover such problems. Please contact the creator of the script instead.
  - name: Autosplitters created by Ero.
    url: https://github.com/just-ero/asl
    about: Please open issues related to auto splitters created by Ero in just-ero/asl.
