name: Create release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The version identifier for the new release.'
        type: string
        required: true
      pre_release:
        description: 'This is a pre-release.'
        type: boolean

permissions:
  contents: write

jobs:
  build-asl-help:
    uses: ./.github/workflows/00_01_build-asl-help.yml

  create-changelog:
    uses: ./.github/workflows/01_00_create-changelog.yml
    with:
      tag: ${{ inputs.tag }}
      pre_release: ${{ inputs.pre_release }}

  create-release:
    needs: [ build-asl-help, create-changelog ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout asl-help
        uses: actions/checkout@v4

      - name: Load cached asl-help.dll from artifacts
        uses: actions/download-artifact@v4
        with:
          name: asl-help-dll

      - name: Delete cached asl-help.dll from artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: asl-help-dll
          failOnError: false

      - name: Create release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ inputs.tag }}
          release_name: ${{ inputs.tag }}
          body: ${{ needs.create-changelog.outputs.changelog }}
          prerelease: ${{ github.event.inputs.pre_release }}

      - name: Upload asl-help as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./asl-help.dll
          asset_name: asl-help
          asset_content_type: application/octet-stream
